[package]
name = "ct-bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
agent-client-protocol = "0.4.0"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.20"
tungstenite = "0.20"