[package]
name = "ct-bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
agent-client-protocol = "0.4.0"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.20"
tungstenite = "0.20"
futures = "0.3"
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4"] }